services:
  - id: 1,
    name: mongodb
    description: Clustered MongoDB service
    bindable: true
    plans:
      - id: 1
        name: full
        description: Access to whole database
      - id: 2
        name: basic
        description: Access to basic usage
